name: Release
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'QueryOwl v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          updaterJsonPreferNsis: true

  update-repo:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout queryowl-updates repo
        uses: actions/checkout@v4
        with:
          repository: bryansh/queryowl-updates
          token: ${{ secrets.UPDATER_TOKEN }}
          path: updates-repo

      - name: Get release data
        id: release
        run: |
          VERSION="${{ github.ref_name }}"
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          
          # Get release data from API
          RELEASE_DATA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }}")
          
          echo "$RELEASE_DATA" > release.json

      - name: Generate latest.json
        run: |
          VERSION="${{ steps.release.outputs.version }}"
          REPO="${{ github.repository }}"
          
          # Extract download URLs and signatures from release assets
          python3 << 'EOF'
          import json
          import sys
          
          with open('release.json', 'r') as f:
              release = json.load(f)
          
          if 'message' in release:
              print(f"Error: {release['message']}")
              sys.exit(1)
          
          version = "${{ steps.release.outputs.version }}"
          assets = release.get('assets', [])
          
          platforms = {}
          signatures = {}
          
          for asset in assets:
              name = asset['name']
              url = asset['browser_download_url']
              
              if name.endswith('.tar.gz') and 'aarch64-apple-darwin' in name:
                  platforms['darwin-aarch64'] = {'url': url}
              elif name.endswith('.tar.gz') and 'x86_64-apple-darwin' in name:
                  platforms['darwin-x86_64'] = {'url': url}
              elif name.endswith('.AppImage'):
                  platforms['linux-x86_64'] = {'url': url}
              elif name.endswith('.msi'):
                  platforms['windows-x86_64'] = {'url': url}
              elif name.endswith('.sig'):
                  # Extract signature content if available
                  sig_platform = name.replace('.sig', '')
                  if 'aarch64-apple-darwin' in sig_platform:
                      signatures['darwin-aarch64'] = name
                  elif 'x86_64-apple-darwin' in sig_platform:
                      signatures['darwin-x86_64'] = name
                  elif 'AppImage' in sig_platform:
                      signatures['linux-x86_64'] = name
                  elif 'msi' in sig_platform:
                      signatures['windows-x86_64'] = name
          
          # Add signatures to platforms
          for platform in signatures:
              if platform in platforms:
                  platforms[platform]['signature'] = f"See GitHub release for {signatures[platform]}"
          
          latest = {
              "version": version,
              "pub_date": release['published_at'],
              "platforms": platforms
          }
          
          with open('updates-repo/latest.json', 'w') as f:
              json.dump(latest, f, indent=2)
          
          print(f"Generated latest.json for version {version}")
          EOF

      - name: Commit and push updates
        run: |
          cd updates-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add latest.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update to version ${{ steps.release.outputs.version }}"
            git push
          fi